#ifndef SH_DEVICELISTITEM_GLOBAL_H
#define SH_DEVICELISTITEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SH_DEVICELISTITEM_LIBRARY)
#  define SH_DEVICELISTITEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SH_DEVICELISTITEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SH_DEVICELISTITEM_GLOBAL_H
